### ISSUE TITLE
[feature] Credential store extensions

### ISSUE THREAD

**Issue by frozencemetery** [heimdal/heimdal#126] opened 2015-04-22 19:18 UTC
Heimdal does not currently have support for the [Credential Store extensions](http://k5wiki.kerberos.org/wiki/Projects/Credential_Store_extensions).  Especially missing for my purposes is `gss_acquire_cred_from()`, without which it's somewhat painful to specify, e.g., a keytab location in a config file.

Thanks!

**Comment by nicowilliams** [comment] 2015-04-22 21:29
Yes, we should add these, at least gss_acquire_cred_from().
gss_store_cred_into() may not be very well-thought out.

Nico
--

**Comment by lhoward** [comment] 2018-12-26 09:37
Duplicate of #451

**Closed by lhoward** 2018-12-26 09:37 UTC
Labels: feature request
