### ISSUE TITLE
klist does not allow to read foreign cache files

### ISSUE THREAD

**Issue by rhopfer** [heimdal/heimdal#306] opened 2017-07-26 16:27 UTC
It should be possible to read a foreign cache file as you can do with MIT Kerberos.
If you have a file
```
ls -l /tmp/krb5cc_1000_*
-rw------- 1 user users 551 Jul 26 18:04 /tmp/krb5cc_1000_wu20I96RjI
```
and I try to read it as root you get:
```
klist -c /tmp/krb5cc_1000_wu20I96RjI
klist: krb5_cc_get_principal: Refuses to open cache files not own by myself FILE:/tmp/krb5cc_1000_wu20I96RjI (owned by 1000)
```
For me this makes no sense because it gives not more security (because you can copy the file) but makes it more complicated for the system administrator.

**Comment by jaltman** [comment] 2017-07-26 16:34
The implemented behavior is correct.  It protects the user from writing a credential to the file that the file owner would not have access to themselves.

**Comment by rhopfer** [comment] 2017-07-26 16:57
1. With `klist` it is only possible to read from a file
2. It is the job of the file system to give read/write permissions
3. It is the behavior of MIT Kerberos, so it is inconsitent with the reference implementation

**Comment by elric1** [comment] 2017-07-26 19:53
It also protects you from *using* a credential that isn't yours.  This is a little subtle but there are many situations where the actions of a program may be driven by external data.  In this case, if you use a credential that is not yours then you can be MITMed by the owner of the credential and caused to take actions based on the false information that they provide.

**Comment by nicowilliams** [comment] 2017-07-26 20:14
> It should be possible to read a foreign cache file as you can do with MIT Kerberos.
> If you have a file
> ```
> ls -l /tmp/krb5cc_1000_*
> -rw------- 1 user users 551 Jul 26 18:04 /tmp/krb5cc_1000_wu20I96RjI
> ```
> and I try to read it as root you get:
> ```
> klist -c /tmp/krb5cc_1000_wu20I96RjI
> klist: krb5_cc_get_principal: Refuses to open cache files not own by myself FILE:/tmp/krb5cc_1000_wu20I96RjI (owned by 1000)
> ```

You can always just `su -c user "klist -c /tmp/krb5cc_1000_wu20I96RjI"`.

> For me this makes no sense because it gives not more security (because you can copy the file) but makes it more complicated for the system administrator.

This is probably a bit overly paranoid on the part of Heimdal, but it has some benefits in terms of security analysis, particularly with respect to symlink-following attacks on TMPDIRs (especially on systems without O_NOFOLLOW and such options).  It also makes it harder (but not impossible) for users to share credentials, which is generally desirable.

**Comment by rhopfer** [comment] 2017-08-07 13:44
I understand the principle not to use a cache which is not yours or is unsafe in other way. But I do not understand why it should be a problem just to show the cache content using `klist`.
If I read it right, `krb5_cc_get_principal` checks all the security stuff, but `display_v5_ccache` decide to print it out. 
Why not printing out a additional warning instead of full deny? Additionally maybe add a command line switch for strict checking?

Btw: Here is a real life example from Debian 9.
attacker:
```
$ cp /tmp/krb5cc_666 /tmp/krb5cc_1000
$ chmod 644 /tmp/krb5cc_1000
```
user:
```
$ ls -ln /tmp/krb5cc_1000
-rw-r--r-- 1 666 100 551 Aug  7 14:13 krb5cc_1000
$ klist
klist: krb5_cc_get_principal: Refuses to open cache files not own by myself FILE:/tmp/krb5cc_1000 (owned by 666)
$ ldapwhoami -Y GSSAPI
dn:uid=attacker,cn=example.org,cn=gssapi,cn=auth
```
Same with SSH. Probably both are linked against mit-krb5, but the client tools are from Heimdal.

**Comment by nicowilliams** [comment] 2017-09-25 22:18
@rhopfer The problem is that the ccache API doesn't know if it is being used by `klist` or in order to authenticate to a remote principal -- the latter is bad if you did not mean to use that ccache (if you got fooled into using a ccache you could read but which isn't yours).  Getting around this would require an API that `klist` can call to say "don't perform such paranoid checks".

**Comment by vdukhovni** [comment] 2018-12-14 20:07
Closing, this is unlikely to be implemented.

**Closed by vdukhovni** 2018-12-14 20:07 UTC
Labels: feature request
