### ISSUE TITLE
Linker error with latest  master branch build (cross-compilation)

### ISSUE THREAD

**Issue by jpadhye** [heimdal/heimdal#106] opened 2014-06-18 03:49 UTC
I'm trying to build the latest code from the master branch. I'm trying to do a 64 bit cross-compile on a 32 bit machine. I was able to compile successfully with the 1.5.3 build. I've checked that the symbols are exported in the version-script.map file. Can somebody pass some pointers how to get past this?

I'm getting the following error:

```
./../include/roken.h:366:1: warning: "EWOULDBLOCK" redefined
In file included from buildtools/nptl/linux-2.6.10/gcc-4.1.1-glibc-2.3.6-mallocfix/x86_64-unknown-linux-gnu/bin/../x86_64-unknown-linux-gnu/sys-root/usr/include/bits/errno.h:25,
                 from /buildtools/nptl/linux-2.6.10/gcc-4.1.1-glibc-2.3.6-mallocfix/x86_64-unknown-linux-gnu/bin/../x86_64-unknown-linux-gnu/sys-root/usr/include/errno.h:36,
                 from krb5_locl.h:43,
                 from verify_krb5_conf.c:34:
/buildtools/nptl/linux-2.6.10/gcc-4.1.1-glibc-2.3.6-mallocfix/x86_64-unknown-linux-gnu/bin/../x86_64-unknown-linux-gnu/sys-root/usr/include/linux/errno.h:45:1: warning: this is the location of the previous definition
  CCLD   verify_krb5_conf
./.libs/libkrb5.so: undefined reference to `rk_getifaddrs'
./.libs/libkrb5.so: undefined reference to `rk_freeifaddrs'
```

**Comment by DavidMulder** [comment] 2016-08-02 17:41
I also had this issue. I got around it by wrapping those defines in \#if _WIN32_  \#endif

**Comment by jaltman** [comment] 2016-08-02 17:50
@DavidMulder on which platform and with which compiler did you have the issue?

**Comment by DavidMulder** [comment] 2016-08-02 18:00
I believe I saw this on ppc64 linux, with gcc 4.7

**Comment by DavidMulder** [comment] 2016-08-02 19:49
Oh, I was referring to the redefinition warning at the top of that output, not the undefined reference error.

**Comment by nicowilliams** [comment] 2016-11-10 03:57
Steps to reproduce a cross-compilation environment?

**Comment by vdukhovni** [comment] 2017-03-09 22:09
Is this still an issue?

**Comment by winyl77** [comment] 2017-11-08 07:07
Yes this is still a issue on heimdal-7.4.0. I get error during check with verify_krb5_conf binary on lede build system:
```bash
home/lede/staging_dir/toolchain-arm_cortex-a15+neon-vfpv4_gcc-7.2.0_glibc_eabi/lib/gcc/arm-openwrt-linux-gnueabi/7.2.0/../../../../arm-openwrt-linux-gnueabi/bin/ar: `u' modifier ignored since `D' is the default (see `U')
  CC       verify_krb5_conf.o
  CCLD     verify_krb5_conf
./.libs/libkrb5.so: undefined reference to `rk_getpwnam_r'
collect2: error: ld returned 1 exit status
Makefile:1745: recipe for target 'verify_krb5_conf' failed
make[5]: *** [verify_krb5_conf] Error 1
```
But the undefined reference `rk_getpwnam_r' is in the ./.libs/krb5/libkrb5.so:
```bash
home/lede/build_dir/target-arm_cortex-a15+neon-vfpv4_glibc_eabi/heimdal-7.4.0/lib/krb5/.libs$ nm libkrb5.so | grep rk_getpwnam_r
         U rk_getpwnam_r
```
Does verify_krb5_conf really check for it? Because I can not understand why it does not find it?

The error with /* Microsoft VC 2010 POSIX definitions */ still remains in heimdal-7.4.0. Remedied with ifdef _WIN32 :)

**Comment by winyl77** [comment] 2017-11-09 20:02
checked roken library, the mentionted export is in libroken.so:
```bash
/build_dir/target-arm_cortex-a15+neon-vfpv4_glibc_eabi/heimdal-7.4.0/lib/roken/.libs$ readelf -Ws libroken.so | grep "rk_getpwnam_r"
   419: 00005fd8   380 FUNC    LOCAL  DEFAULT   11 rk_getpwnam_r
```
but it is LOCAL! So not met to be called by external code! But in the libroken_la-getxxyyy.o it is GLOBAL:
```bash
build_dir/target-arm_cortex-a15+neon-vfpv4_glibc_eabi/heimdal-7.4.0/lib/roken$ readelf -Ws libroken_la-getxxyyy.o | grep "rk_getpwnam_r"
     9: 00000000   380 FUNC    GLOBAL DEFAULT    1 rk_getpwnam_r
```
So the linker changes it to local somehow when compiling libroken. But how?

**Comment by winyl77** [comment] 2017-11-09 20:10
Found the error!
rk_getpwnam_r is not in the global section of ../lib//roken/version-script.map. Adding it solves the problem.

**Comment by Andy2244** [comment] 2018-01-19 19:40
@winyl77 thx, would have taken me way longer without this to figure out whats happening!

Did run into the same problem on latest openwrt/lede, would be nice to actually add the patch, so we can close this.

**003-missing-rk_getpwnam_r.patch**
```
--- a/lib/roken/version-script.map
+++ b/lib/roken/version-script.map
@@ -73,6 +73,7 @@ HEIMDAL_ROKEN_1.0 {
 		rk_getipnodebyname;
 		rk_getnameinfo;
 		rk_getprogname;
+		rk_getpwnam_r;
 		rk_glob;
 		rk_globfree;
 		rk_hex_decode; 
```

**Comment by jaltman** [comment] 2018-01-19 19:50
The problem is that rk_getpwnam_r() is only compiled as an exportable function if not POSIX_GETPWNAM_R is undefined for the platform.    In order to export the symbol unconditionally, rk_getpwnam_r() must be compiled unconditionally.

**Comment by Andy2244** [comment] 2018-01-19 19:57
@jaltman so whats the proper way to crosscompile than, without this patch? Do we need to patch .configure there are rk_getpwnam_r and $cross_compiling tests, yet we run into this problem?

**Comment by jaltman** [comment] 2018-01-20 17:12
As I indicated in the prior response, rk_getpwnam_r() must be built unconditionally.  That means it cannot be a macro on some platforms and a function on others.

**Comment by esaaprillia** [comment] 2023-05-23 01:04
this problem still exist in version 7.7.1 and 7.8.0 i am trying to make it on openwrt 21.02.7. i need this for freeradius-krb5 on openwrt


```/home/open/port/staging_dir/toolchain-aarch64_cortex-a53_gcc-8.4.0_musl/bin/../lib/gcc/aarch64-openwrt-linux-musl/8.4.0/../../../../aarch64-openwrt-linux-musl/bin/ld: ./.libs/libkrb5.so: undefined reference to `rk_getpwnam_r'                                                                        
/home/open/port/staging_dir/toolchain-aarch64_cortex-a53_gcc-8.4.0_musl/bin/../lib/gcc/aarch64-openwrt-linux-musl/8.4.0/../../../../aarch64-openwrt-linux-musl/bin/ld: ./.libs/libkrb5.so: undefined reference to `_krb5_pk_kx_confirm'                                                                  
collect2: error: ld returned 1 exit status                                                         
make[5]: *** [Makefile:1937: verify_krb5_conf] Error 1```

**Comment by nicowilliams** [comment] 2023-05-25 17:15
@esaaprillia are you writing your own Makefiles?  `./.libs/libkrb5.so: undefined reference to '_krb5_pk_kx_confirm'` seems to indicate that you're missing `lib/krb5/pkinit.o` in the link-edit of `libkrb5.so`, and `./.libs/libkrb5.so: undefined reference to 'rk_getpwnam_r'` seems to imply that you're missing `-lroken` or that `libroken` isn't including `lib/roken/getuserinfo.o`.

**Comment by esaaprillia** [comment] 2023-12-08 05:53
@nicowilliams 

I have successfully created it in openwrt. but we need a patch

```
--- a/lib/roken/version-script.map
+++ b/lib/roken/version-script.map
@@ -73,6 +73,7 @@ HEIMDAL_ROKEN_1.0 {
 		rk_getipnodebyname;
 		rk_getnameinfo;
 		rk_getprogname;
+		rk_getpwnam_r;
 		rk_glob;
 		rk_globfree;
 		rk_hex_decode; 
```

**Comment by esaaprillia** [comment] 2024-01-05 20:20
done

https://github.com/heimdal/heimdal/commit/42e23b1777a7f4205712612dfa22262b51112c6f

**Closed** 2024-01-06 04:13 UTC
Labels: bug
