### ISSUE TITLE
Build of master branch fails on missing 'vis.h'

### ISSUE THREAD

**Issue by iboukris** [heimdal/heimdal#794] opened 2021-07-17 08:48 UTC
$ git clean -dfx
$ autoreconf -if && CFLAGS="-O0 -g" ./configure && make && make check
...
make[3]: Entering directory '/home/admin/git/heimdal/lib/roken'
  CC       rkvis-vis.o
vis.c:79:10: fatal error: vis.h: No such file or directory
   79 | #include <vis.h>
      |          ^~~~~~~

I currently solve it locally with:
cp ./lib/libedit/src/vis.h include/

Does anyone have any idea about this?

**Comment by lhoward** [comment] 2021-08-08 08:17
`vis.h` should be made from `vis.hin` in libroken

Have you rerun `autogen.sh`?

**Comment by jborean93** [comment] 2021-08-08 09:27
I've recently come across this, I just run `autoreconf` before the standard configure/make steps https://gist.github.com/jborean93/3d2093d9c48f3a08486bfc8d38377b2c#file-heimdal-dockerfile-L27-L33.

**Comment by lhoward** [comment] 2021-08-08 09:31
I'm going to close this as can't reproduce (have tested on Linux and macOS). Let me know if it persists.

**Comment by jborean93** [comment] 2021-08-08 09:36
I definitely still reproduce this, if I was to remove the `cp` step in that Dockerfile it fails with

```
vis.c:79:10: fatal error: vis.h: No such file or directory
   79 | #include <vis.h>
      |          ^~~~~~~
compilation terminated.
```

Should I be running `autogen.sh` as another step?

**Comment by lhoward** [comment] 2021-08-08 09:36
OK, reopening!

**Comment by jborean93** [comment] 2021-08-08 09:39
Oh just an FYI this issue is a duplicate with https://github.com/heimdal/heimdal/issues/777. Not sure if you want to consolidate things.

**Comment by lhoward** [comment] 2021-08-08 09:41
Duplicate of #777

**Closed by lhoward** 2021-08-08 09:41 UTC
