### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by ribx** [heimdal/heimdal#164] opened 2016-03-28 09:54 UTC
It's been a while that there was a new release and samba 4.4 does not compile against the latest rc tag. Isn't it time for a new tag, that would work against samba 4.4?

**Comment by quanah** [comment] 2016-03-28 18:52
The best discussion for this is probably on the heimdal devel list, where there's ongoing discussion about a new release.

**Comment by nicowilliams** [comment] 2016-04-15 20:31
We're getting ready to do a 1.7rc1.

Only two things left now as far as I'm concerned:

 - a small patch to ipropd-master.c and ipropd-slave.c to prevent one last race condition in iprop
 - either improvements to the thread-safety of rand-fortuna.c or a new RAND_METHOD based on the Keccak SpongePRNG, also with thread safety

(The last item also will require a threaded test.)

We should try to close as many issues / merge as many PRs as possible.  This is a call to committers to help with this task.

**Comment by quanah** [comment] 2016-04-15 20:45
Thanks Nico!

**Comment by nicowilliams** [comment] 2016-11-15 04:03
It looks like we're ready.

**Comment by nicowilliams** [comment] 2016-11-18 18:44
I do believe it's ready.

**Comment by jelmer** [comment] 2016-11-19 22:07
There are at least three tests that fail for me in current master:

FAIL: check-gssmask
FAIL: check-context
FAIL: check-spnego

morgaine:~/src/heimdal% cat ./tests/gss/check-gssmask.log
Creating database
Doing database check
Starting kdc
Waiting for KDC to start, looking logfile messages.log
Have waited 2 seconds
Starting client 1
Starting client 2
Starting client 3
gssmaestro: krb5_ret_int32 *hContext
Connecting to slaves
Test acquire credentials
Self context tests
n1 connects to self using host/n1.test.h5l.se@TEST.H5L.SE
gssmask: krb5_ret_int32 op
gssmask: krb5_ret_int32 op
killing kdc and clients (1097, 1360, 1361, 1362)
FAIL check-gssmask (exit status: 1)

**Comment by jaltman** [comment] 2016-11-20 05:01
Fixed by d9f7718a42d25ade77c26dab1a613d383db3b7db.  I still have a significant number of resource leaks to look into.

**Comment by jelmer** [comment] 2016-11-20 17:45
I'm also seeing failures in test_cc in a clean debian chroot, though I haven't been able to reproduce that locally yet.

**Comment by jaltman** [comment] 2016-11-20 18:28
@jelmer I am not able to reproduce a test_cc failure on fedora-25

**Comment by jelmer** [comment] 2016-11-20 18:33
Thanks for checking.

So far I have only managed to reproduce it on our build system (with a clean chroot and minimal dependencies) and not on my local machine. I will file a bug with details when I discover more.

**Comment by nicowilliams** [comment] 2016-12-05 00:20
Regarding protocol for fixing things in the release branch(es), @vdukhovni and I propose:

 - all fixes go to `master` first unless they are specific to the branch in question
 - all fixes to tests that go to `master` can be pulled into the branch without further ado
 - all other fixes need additional review prior to pulling into the branch

**Comment by jelmer** [comment] 2016-12-10 19:31
There are a number of (what look like) architecture-related test issues in RC1. E.g. on i386/kfreebsd-i386/powerpc a number of the gss tests fail (check-basic, check-context, check-spnego, check-ntlm). On hppa/powerpcspe some of the kdc tests fail.

Incidentally, is there an easy way to get "make test" to dump test logs for tests that fail to stdout?

**Comment by jelmer** [comment] 2016-12-14 15:11
What are the current plans/schedule for 7.1?

**Comment by jaltman** [comment] 2016-12-14 16:30
@jelmer There will need to be at least one more release candidate to obtain test results for fixed bugs.  In addition, there is something broken in the Windows builds related to credential cache plugins that I have as yet been unable to track down.

**Comment by jelmer** [comment] 2016-12-25 15:19
Now that 7.1 is out I think this can be closed.

**Closed** 2016-12-25 15:26 UTC

**Comment by glensc** [comment] 2016-12-26 16:30
well, 7.1 i'd ask? nothing on github release notes why the versioning change, nothing in project readme, and even the github page sends to http://www.h5l.org/ which still speaks of 1.5

**Comment by lha** [comment] 2016-12-26 17:50
webpage updated with the release.

Love
